{
    "openapi": "3.0.0",
    "info": {
        "title": "Product API",
        "description": "Product API with Auth + JWT",
        "contact": {
            "email": "hadiatab16@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:8000/api/v1",
            "description": "Demo API Product"
        }
    ],
    "paths": {
        "/register": {
            "post": {
                "tags": [
                    "Authentication"
                ],
                "summary": "Register Account",
                "description": "Create new account for accessing data",
                "operationId": "registration",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "email": "test@email.com",
                                    "password": "test1234"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Ok",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "success",
                                    "message": "User created successfully",
                                    "user": {
                                        "name": "hab",
                                        "email": "hab@email.com",
                                        "updated_at": "2024-08-10T09:54:57.000000Z",
                                        "created_at": "2024-08-10T09:54:57.000000Z",
                                        "id": 1
                                    },
                                    "authorization": {
                                        "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL3JlZ2lzdGVyIiwiaWF0IjoxNzIzMjgzNjk3LCJleHAiOjE3MjMyODcyOTcsIm5iZiI6MTcyMzI4MzY5NywianRpIjoiTXpKdjQ4b2RkRGpFSFM4RCIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.UcjMqKzsI58tcHvtC23s6fGD8xIrqTTCMUEtrg9RnsM",
                                        "type": "bearer"
                                    }
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Content"
                    }
                }
            }
        },
        "/login": {
            "post": {
                "tags": [
                    "Authentication"
                ],
                "summary": "Login Account",
                "description": "Login to account",
                "operationId": "login",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "email": "test@email.com",
                                    "password": "test1234"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Ok",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "success",
                                    "message": "User created successfully",
                                    "user": {
                                        "name": "hab",
                                        "email": "hab@email.com",
                                        "updated_at": "2024-08-10T09:54:57.000000Z",
                                        "created_at": "2024-08-10T09:54:57.000000Z",
                                        "id": 1
                                    },
                                    "authorization": {
                                        "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL3JlZ2lzdGVyIiwiaWF0IjoxNzIzMjgzNjk3LCJleHAiOjE3MjMyODcyOTcsIm5iZiI6MTcyMzI4MzY5NywianRpIjoiTXpKdjQ4b2RkRGpFSFM4RCIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.UcjMqKzsI58tcHvtC23s6fGD8xIrqTTCMUEtrg9RnsM",
                                        "type": "bearer"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "422": {
                        "description": "Unprocessable Content"
                    }
                }
            }
        },
        "/me": {
            "get": {
                "tags": [
                    "Authentication"
                ],
                "summary": "User Info",
                "description": "Get detail user",
                "operationId": "me",
                "responses": {
                    "200": {
                        "description": "Ok",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "success",
                                    "message": "User created successfully",
                                    "user": {
                                        "name": "hab",
                                        "email": "hab@email.com",
                                        "updated_at": "2024-08-10T09:54:57.000000Z",
                                        "created_at": "2024-08-10T09:54:57.000000Z",
                                        "id": 1
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/logout": {
            "post": {
                "tags": [
                    "Authentication"
                ],
                "summary": "Log the user out",
                "description": "Invalidate the token.",
                "operationId": "logout",
                "responses": {
                    "200": {
                        "description": "Successfully logged out",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "success",
                                    "message": "Successfully logged out"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/refresh": {
            "get": {
                "tags": [
                    "Authentication"
                ],
                "summary": "Refresh the token",
                "description": "Generate a new token.",
                "operationId": "refreshToken",
                "responses": {
                    "200": {
                        "description": "Token refreshed"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/category-products": {
            "get": {
                "tags": [
                    "Category Products"
                ],
                "summary": "List all category products",
                "operationId": "allCategoryProduct",
                "responses": {
                    "200": {
                        "description": "Category products found",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "success",
                                    "message": "Category Product found",
                                    "data": "Array of category product"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Category Products"
                ],
                "summary": "Create a new category product",
                "operationId": "storeCategoryProduct",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "name"
                                ],
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "example": "New Category"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Category Product created successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "success",
                                    "message": "Category Product created successfully",
                                    "data": {
                                        "id": 1,
                                        "name": "New Category"
                                    }
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Validation errors",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "failed",
                                    "message": "create Category Product failed!",
                                    "errors": {
                                        "name": "array of error"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/category-products/{id}": {
            "get": {
                "tags": [
                    "Category Products"
                ],
                "summary": "Get a category product by ID",
                "operationId": "showCategoryProduct",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Category Product found",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "success",
                                    "message": "Category Product found",
                                    "data": {
                                        "id": 1,
                                        "name": "HP"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Category Product not found",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "failed",
                                    "message": "Category Product not found"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "Category Products"
                ],
                "summary": "Update an existing category product",
                "description": "Update the specified resource in storage.",
                "operationId": "updateCategoryProduct",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "name"
                                ],
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "example": "Updated Category"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Category Product updated successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "success",
                                    "message": "Category Product updated successfully",
                                    "data": {
                                        "id": 1,
                                        "name": "Updated Category"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Category Product not found",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "failed",
                                    "message": "Category Product not found"
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Validation errors",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "failed",
                                    "message": "update Category Product failed!",
                                    "errors": {
                                        "name": "array of error"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Category Products"
                ],
                "summary": "Delete a category product",
                "description": "Remove the specified resource from storage.",
                "operationId": "deleteCategoryProduct",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Category Product deleted successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "success",
                                    "message": "Category Product deleted successfully!"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Category Product not found",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "failed",
                                    "message": "Category Product not found"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        }
    },
    "components": {
        "responses": {
            "401": {
                "description": "Unauthorized"
            }
        },
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "description": "Enter JWT token to access these endpoints",
                "bearerFormat": "JWT",
                "scheme": "bearer"
            }
        }
    },
    "tags": [
        {
            "name": "Authentication",
            "description": "Authentication"
        },
        {
            "name": "Category Products",
            "description": "Category Products"
        }
    ]
}